import { BackSide, Color, Euler, Vector3 } from 'three'
import { IDBroker } from './utils/id-broker'

export const MENU_INITIAL_KEY = 'PRINCIPAL'

// ACTIONS project
export const SET_USER_AUTHENTICATED = 'SET_USER_AUTHENTICATED'
export const SET_PREFERENCES = 'SET_PREFERENCES'
export const UPDATE_PREFERENCE = 'UPDATE_PREFERENCE'
export const UPDATE_PREFERENCE_COMPLETED = 'UPDATE_PREFERENCE_COMPLETED'
export const UPDATE_PREFERENCE_FAILED = 'UPDATE_PREFERENCE_FAILED'
export const NEXT_DRAWING_ITEM = 'NEXT_DRAWING_ITEM'
export const NEW_PROJECT = 'NEW_PROJECT'
export const LOAD_PROJECT = 'LOAD_PROJECT'
export const SAVE_PROJECT = 'SAVE_PROJECT'
export const OPEN_CATALOG = 'OPEN_CATALOG'
export const SELECT_TOOL_EDIT = 'SELECT_TOOL_EDIT'
export const UNSELECT_ALL = 'UNSELECT_ALL'
export const SET_PROPERTIES = 'SET_PROPERTIES'
export const SET_ITEMS_ATTRIBUTES = 'SET_ITEMS_ATTRIBUTES'
export const SET_LINES_ATTRIBUTES = 'SET_LINES_ATTRIBUTES'
export const SET_HOLES_ATTRIBUTES = 'SET_HOLES_ATTRIBUTES'
export const REMOVE = 'REMOVE'
export const UNDO = 'UNDO'
export const ROLLBACK = 'ROLLBACK'
export const SET_PROJECT_PROPERTIES = 'SET_PROJECT_PROPERTIES'
export const OPEN_PROJECT_CONFIGURATOR = 'OPEN_PROJECT_CONFIGURATOR'
export const INIT_CATALOG = 'INIT_CATALOG'
export const UPDATE_MOUSE_COORDS = 'UPDATE_MOUSE_COORDS'
export const UPDATE_ZOOM_SCALE = 'UPDATE_ZOOM_SCALE'
export const TOGGLE_SNAP = 'TOGGLE_SNAP'
export const CHANGE_CATALOG_PAGE = 'CHANGE_CATALOG_PAGE'
export const GO_BACK_TO_CATALOG_PAGE = 'GO_BACK_TO_CATALOG_PAGE'
export const THROW_ERROR = 'THROW_ERROR'
export const THROW_WARNING = 'THROW_WARNING'
export const COPY_PROPERTIES = 'COPY_PROPERTIES'
export const PASTE_PROPERTIES = 'PASTE_PROPERTIES'
export const PUSH_LAST_SELECTED_CATALOG_ELEMENT_TO_HISTORY =
  'PUSH_LAST_SELECTED_CATALOG_ELEMENT_TO_HISTORY'
export const ALTERATE_STATE = 'ALTERATE_STATE'
export const SET_MODE = 'SET_MODE'
export const ADD_HORIZONTAL_GUIDE = 'ADD_HORIZONTAL_GUIDE'
export const ADD_VERTICAL_GUIDE = 'ADD_VERTICAL_GUIDE'
export const ADD_CIRCULAR_GUIDE = 'ADD_CIRCULAR_GUIDE'
export const REMOVE_HORIZONTAL_GUIDE = 'REMOVE_HORIZONTAL_GUIDE'
export const REMOVE_VERTICAL_GUIDE = 'REMOVE_VERTICAL_GUIDE'
export const REMOVE_CIRCULAR_GUIDE = 'REMOVE_CIRCULAR_GUIDE'
export const SET_IS_ELEMENT_SELECTED = 'SET_IS_ELEMENT_SELECTED'
export const ENABLE_WALLS_MODAL = 'ENABLE_WALLS_MODAL'
export const DISABLE_WALLS_MODAL = 'DISABLE_WALLS_MODAL'
export const ENABLE_CONFIRM_MODAL = 'ENABLE_CONFIRM_MODAL'
export const DISABLE_CONFIRM_MODAL = 'DISABLE_CONFIRM_MODAL'
export const SET_SELECTED_ROOM = 'SET_SELECTED_ROOM'
export const SET_PREDEFINED_LINES = 'SET_PREDEFINED_LINES'
export const SET_IS_NEW_PROJECT = 'SET_IS_NEW_PROJECT'
export const UNSET_IS_NEW_PROJECT = 'UNSET_IS_NEW_PROJECT'
export const SET_ATTRIBUTES_ON_SELECTED_INPUT = 'SET_ATTRIBUTES_ON_SELECTED_INPUT'
export const SET_PROPERTIES_ON_SELECTED_INPUT = 'SET_PROPERTIES_ON_SELECTED_INPUT'
export const RECALC_VERTEX_BY_LINE = 'RECALC_VERTEX_BY_LINE'
export const RECALC_VERTEX_BY_VERTEX = 'RECALC_VERTEX_BY_VERTEX'

// ACTIONS viewer2D
export const SELECT_TOOL_ZOOM_IN = 'SELECT_TOOL_ZOOM_IN'
export const SELECT_TOOL_ZOOM_OUT = 'SELECT_TOOL_ZOOM_OUT'
export const SELECT_TOOL_PAN = 'SELECT_TOOL_PAN'
export const UPDATE_2D_CAMERA = 'UPDATE_2D_CAMERA'

//ACTIONS viewer3D
export const SELECT_TOOL_3D_VIEW = 'SELECT_TOOL_3D_VIEW'
export const SELECT_TOOL_3D_FIRST_PERSON = 'SELECT_TOOL_3D_FIRST_PERSON'

//ACTIONS items
export const SELECT_TOOL_DRAWING_ITEM = 'SELECT_TOOL_DRAWING_ITEM'
export const SELECT_TOOL_DRAWING_ITEM_3D = 'SELECT_TOOL_DRAWING_ITEM_3D'
export const UPDATE_DRAWING_ITEM = 'UPDATE_DRAWING_ITEM'
export const END_DRAWING_ITEM = 'END_DRAWING_ITEM'
export const END_DRAWING_ITEM_3D = 'END_DRAWING_ITEM_3D'
export const BEGIN_DRAGGING_ITEM = 'BEGIN_DRAGGING_ITEM'
export const BEGIN_DRAGGING_ITEM_3D = 'BEGIN_DRAGGING_ITEM_3D'
export const UPDATE_DRAGGING_ITEM = 'UPDATE_DRAGGING_ITEM'
export const UPDATE_DRAGGING_ITEM_3D = 'UPDATE_DRAGGING_ITEM_3D'
export const END_DRAGGING_ITEM = 'END_DRAGGING_ITEM'
export const END_DRAGGING_ITEM_3D = 'END_DRAGGING_ITEM_3D'
export const BEGIN_ROTATING_ITEM = 'BEGIN_ROTATING_ITEM'
export const UPDATE_ROTATING_ITEM = 'UPDATE_ROTATING_ITEM'
export const END_ROTATING_ITEM = 'END_ROTATING_ITEM'

//ACTIONS groups
export const ADD_GROUP = 'ADD_GROUP'
export const ADD_GROUP_FROM_SELECTED = 'ADD_GROUP_FROM_SELECTED'
export const SELECT_GROUP = 'SELECT_GROUP'
export const UNSELECT_GROUP = 'UNSELECT_GROUP'
export const ADD_TO_GROUP = 'ADD_TO_GROUP'
export const REMOVE_FROM_GROUP = 'REMOVE_FROM_GROUP'
export const SET_GROUP_PROPERTIES = 'SET_GROUP_PROPERTIES'
export const SET_GROUP_ATTRIBUTES = 'SET_GROUP_ATTRIBUTES'
export const SET_GROUP_BARYCENTER = 'SET_GROUP_BARYCENTER'
export const REMOVE_GROUP = 'REMOVE_GROUP'
export const REMOVE_GROUP_AND_DELETE_ELEMENTS = 'REMOVE_GROUP_AND_DELETE_ELEMENTS'
export const GROUP_TRANSLATE = 'GROUP_TRANSLATE'
export const GROUP_ROTATE = 'GROUP_ROTATE'

//ACTION drawings
export const SELECT_HOLE = 'SELECT_HOLE'
export const SELECT_AREA = 'SELECT_AREA'
export const SELECT_ITEM = 'SELECT_ITEM'
export const SELECT_LINE = 'SELECT_LINE'
export const SELECT_TOOL_DRAWING_LINE = 'SELECT_TOOL_DRAWING_LINE'
export const BEGIN_DRAWING_LINE = 'BEGIN_DRAWING_LINE'
export const UPDATE_DRAWING_LINE = 'UPDATE_DRAWING_LINE'
export const END_DRAWING_LINE = 'END_DRAWING_LINE'
export const SELECT_TOOL_DRAWING_HOLE = 'SELECT_TOOL_DRAWING_HOLE'
export const UPDATE_DRAWING_HOLE = 'UPDATE_DRAWING_HOLE' //SHOULD BE SLPITTED IN BEGIN_DRAWING_HOLE AND UPDATE_DRAWING_HOLE
export const END_DRAWING_HOLE = 'END_DRAWING_HOLE'
export const BEGIN_DRAGGING_LINE = 'BEGIN_DRAGGING_LINE'
export const UPDATE_DRAGGING_LINE = 'UPDATE_DRAGGING_LINE'
export const END_DRAGGING_LINE = 'END_DRAGGING_LINE'
export const SELECT_TOOL_UPLOAD_IMAGE = 'SELECT_TOOL_UPLOAD_IMAGE'
export const BEGIN_UPLOADING_IMAGE = 'BEGIN_UPLOADING_IMAGE'
export const END_UPLOADING_IMAGE = 'END_UPLOADING_IMAGE'
export const BEGIN_FITTING_IMAGE = 'BEGIN_FITTING_IMAGE'
export const END_FITTING_IMAGE = 'END_FITTING_IMAGE'
export const BEGIN_DRAGGING_HOLE = 'BEGIN_DRAGGING_HOLE'
export const UPDATE_DRAGGING_HOLE = 'UPDATE_DRAGGING_HOLE'
export const END_DRAGGING_HOLE = 'END_DRAGGING_HOLE'
export const CACHE_FONDO = 'CACHE_FONDO'
export const CACHE_ALTO = 'CACHE_ALTO'
export const CACHE_ANGULO = 'CACHE_ANGULO'

//ACTIONS vertices
export const BEGIN_DRAGGING_VERTEX = 'BEGIN_DRAGGING_VERTEX'
export const UPDATE_DRAGGING_VERTEX = 'UPDATE_DRAGGING_VERTEX'
export const END_DRAGGING_VERTEX = 'END_DRAGGING_VERTEX'
export const DRAG_VERTEX = 'DRAG_VERTEX'

//ACTIONS scene
export const SET_LAYER_PROPERTIES = 'SET_LAYER_PROPERTIES'
export const ADD_LAYER = 'ADD_LAYER'
export const SELECT_LAYER = 'SELECT_LAYER'
export const REMOVE_LAYER = 'REMOVE_LAYER'

//GROUPING ACTIONS
export const PROJECT_ACTIONS = {
  SET_USER_AUTHENTICATED,
  SET_PREFERENCES,
  UPDATE_PREFERENCE,
  UPDATE_PREFERENCE_COMPLETED,
  UPDATE_PREFERENCE_FAILED,
  NEW_PROJECT,
  LOAD_PROJECT,
  SAVE_PROJECT,
  OPEN_CATALOG,
  SELECT_TOOL_EDIT,
  UNSELECT_ALL,
  SET_PROPERTIES,
  NEXT_DRAWING_ITEM,
  SET_ITEMS_ATTRIBUTES,
  SET_LINES_ATTRIBUTES,
  SET_HOLES_ATTRIBUTES,
  REMOVE,
  UNDO,
  ROLLBACK,
  SET_PROJECT_PROPERTIES,
  OPEN_PROJECT_CONFIGURATOR,
  INIT_CATALOG,
  UPDATE_MOUSE_COORDS,
  UPDATE_ZOOM_SCALE,
  TOGGLE_SNAP,
  CHANGE_CATALOG_PAGE,
  GO_BACK_TO_CATALOG_PAGE,
  THROW_ERROR,
  THROW_WARNING,
  COPY_PROPERTIES,
  PASTE_PROPERTIES,
  PUSH_LAST_SELECTED_CATALOG_ELEMENT_TO_HISTORY,
  ALTERATE_STATE,
  SET_MODE,
  ADD_HORIZONTAL_GUIDE,
  ADD_VERTICAL_GUIDE,
  ADD_CIRCULAR_GUIDE,
  REMOVE_HORIZONTAL_GUIDE,
  REMOVE_VERTICAL_GUIDE,
  REMOVE_CIRCULAR_GUIDE,
  SET_IS_ELEMENT_SELECTED,
  ENABLE_WALLS_MODAL,
  DISABLE_WALLS_MODAL,
  ENABLE_CONFIRM_MODAL,
  DISABLE_CONFIRM_MODAL,
  SET_SELECTED_ROOM,
  SET_PREDEFINED_LINES,
  SET_ATTRIBUTES_ON_SELECTED_INPUT,
  SET_PROPERTIES_ON_SELECTED_INPUT,
  SET_IS_NEW_PROJECT,
  UNSET_IS_NEW_PROJECT,
}

export const VIEWER2D_ACTIONS = {
  SELECT_TOOL_ZOOM_IN,
  SELECT_TOOL_ZOOM_OUT,
  SELECT_TOOL_PAN,
  UPDATE_2D_CAMERA,
}

export const VIEWER3D_ACTIONS = {
  SELECT_TOOL_3D_VIEW,
  SELECT_TOOL_3D_FIRST_PERSON,
}

export const ITEMS_ACTIONS = {
  SELECT_ITEM,
  SELECT_TOOL_DRAWING_ITEM,
  UPDATE_DRAWING_ITEM,
  END_DRAWING_ITEM,
  BEGIN_DRAGGING_ITEM,
  UPDATE_DRAGGING_ITEM,
  END_DRAGGING_ITEM,
  BEGIN_ROTATING_ITEM,
  UPDATE_ROTATING_ITEM,
  END_ROTATING_ITEM,
  SELECT_TOOL_DRAWING_ITEM_3D,
  BEGIN_DRAGGING_ITEM_3D,
  UPDATE_DRAGGING_ITEM_3D,
  END_DRAGGING_ITEM_3D,
}

export const HOLE_ACTIONS = {
  SELECT_HOLE,
  SELECT_TOOL_DRAWING_HOLE,
  UPDATE_DRAWING_HOLE,
  END_DRAWING_HOLE,
  BEGIN_DRAGGING_HOLE,
  UPDATE_DRAGGING_HOLE,
  END_DRAGGING_HOLE,
}

export const LINE_ACTIONS = {
  SELECT_LINE,
  SELECT_TOOL_DRAWING_LINE,
  BEGIN_DRAWING_LINE,
  UPDATE_DRAWING_LINE,
  END_DRAWING_LINE,
  BEGIN_DRAGGING_LINE,
  UPDATE_DRAGGING_LINE,
  END_DRAGGING_LINE,
  CACHE_ALTO,
  CACHE_FONDO,
  CACHE_ANGULO,
  RECALC_VERTEX_BY_LINE,
}

export const AREA_ACTIONS = {
  SELECT_AREA,
}

export const GROUP_ACTIONS = {
  ADD_GROUP,
  ADD_GROUP_FROM_SELECTED,
  SELECT_GROUP,
  UNSELECT_GROUP,
  ADD_TO_GROUP,
  REMOVE_FROM_GROUP,
  SET_GROUP_PROPERTIES,
  SET_GROUP_ATTRIBUTES,
  SET_GROUP_BARYCENTER,
  REMOVE_GROUP,
  REMOVE_GROUP_AND_DELETE_ELEMENTS,
  GROUP_TRANSLATE,
  GROUP_ROTATE,
}

export const SCENE_ACTIONS = {
  ADD_LAYER,
  SET_LAYER_PROPERTIES,
  SELECT_LAYER,
  REMOVE_LAYER,
}

export const VERTEX_ACTIONS = {
  BEGIN_DRAGGING_VERTEX,
  UPDATE_DRAGGING_VERTEX,
  END_DRAGGING_VERTEX,
  DRAG_VERTEX,
  RECALC_VERTEX_BY_VERTEX,
}

//MODES
export const MODE_IDLE = 'MODE_IDLE'
export const MODE_2D_ZOOM_IN = 'MODE_2D_ZOOM_IN'
export const MODE_2D_ZOOM_OUT = 'MODE_2D_ZOOM_OUT'
export const MODE_2D_PAN = 'MODE_2D_PAN'
export const MODE_3D_VIEW = 'MODE_3D_VIEW'
export const MODE_3D_FIRST_PERSON = 'MODE_3D_FIRST_PERSON'
export const MODE_WAITING_DRAWING_LINE = 'MODE_WAITING_DRAWING_LINE'
export const MODE_DRAGGING_LINE = 'MODE_DRAGGING_LINE'
export const MODE_DRAGGING_VERTEX = 'MODE_DRAGGING_VERTEX'
export const MODE_DRAGGING_ITEM = 'MODE_DRAGGING_ITEM'
export const MODE_DRAGGING_ITEM_3D = 'MODE_DRAGGING_ITEM_3D'
export const MODE_DRAGGING_HOLE = 'MODE_DRAGGING_HOLE'
export const MODE_DRAWING_LINE = 'MODE_DRAWING_LINE'
export const MODE_DRAWING_HOLE = 'MODE_DRAWING_HOLE'
export const MODE_WAITING_DRAWING_ITEM = 'MODE_WAITING_DRAWING_ITEM'
export const MODE_DRAWING_ITEM = 'MODE_DRAWING_ITEM'
export const MODE_ROTATING_ITEM = 'MODE_ROTATING_ITEM'
export const MODE_UPLOADING_IMAGE = 'MODE_UPLOADING_IMAGE'
export const MODE_FITTING_IMAGE = 'MODE_FITTING_IMAGE'
export const MODE_VIEWING_CATALOG = 'MODE_VIEWING_CATALOG'
export const MODE_CONFIGURING_PROJECT = 'MODE_CONFIGURING_PROJECT'

export const MODES_2D_VIEWER = [
  MODE_IDLE,
  MODE_2D_ZOOM_IN,
  MODE_2D_ZOOM_OUT,
  MODE_2D_PAN,
  MODE_WAITING_DRAWING_LINE,
  MODE_DRAGGING_LINE,
  MODE_DRAGGING_VERTEX,
  MODE_DRAGGING_ITEM,
  MODE_DRAWING_LINE,
  MODE_WAITING_DRAWING_LINE,
  MODE_WAITING_DRAWING_ITEM,
  MODE_DRAWING_HOLE,
  MODE_DRAWING_ITEM,
  MODE_DRAGGING_HOLE,
  MODE_ROTATING_ITEM,
]

//Thinking about it...
//https://developer.mozilla.org/it/docs/Web/JavaScript/Reference/Global_Objects/Proxy
/*
let MODE_DEF = [
  'IDLE',
  '2D_ZOOM_IN',
  '2D_ZOOM_OUT',
  '2D_PAN',
  '3D_VIEW',
  '3D_FIRST_PERSON',
  'WAITING_DRAWING_LINE',
  'DRAGGING_LINE',
  'DRAGGING_VERTEX',
  'DRAGGING_ITEM',
  'DRAGGING_HOLE',
  'DRAWING_LINE',
  'DRAWING_HOLE',
  'DRAWING_ITEM',
  'ROTATING_ITEM',
  'UPLOADING_IMAGE',
  'FITTING_IMAGE',
  'VIEWING_CATALOG',
  'CONFIGURING_PROJECT',
];

export const MODE = new Proxy( MODE_DEF, { get: (target, name) => { return target.indexOf(name) !== -1 ? name : null } } );
*/

export const MODE_SNAPPING = [
  MODE_IDLE,
  MODE_2D_ZOOM_IN,
  MODE_2D_ZOOM_OUT,
  MODE_2D_PAN,
  MODE_WAITING_DRAWING_LINE,
  MODE_DRAWING_LINE,
  MODE_DRAWING_HOLE,
  MODE_DRAWING_ITEM,
  MODE_WAITING_DRAWING_ITEM,
  MODE_DRAGGING_LINE,
  MODE_DRAGGING_VERTEX,
  MODE_DRAGGING_ITEM,
  MODE_DRAGGING_ITEM_3D,
  MODE_DRAGGING_HOLE,
  MODE_FITTING_IMAGE,
  MODE_UPLOADING_IMAGE,
  MODE_ROTATING_ITEM,
]

//UNITS
export const UNIT_MILLIMETER = 'mm'
export const UNIT_CENTIMETER = 'cm'
export const UNIT_METER = 'm'
export const UNIT_INCH = 'in'
export const UNIT_FOOT = 'ft'
export const UNIT_MILE = 'mi'
export const BASE_ZOOM = 9.4 // 9.4

export const UNITS_LENGTH = [
  UNIT_MILLIMETER,
  UNIT_CENTIMETER,
  UNIT_METER,
  UNIT_INCH,
  UNIT_FOOT,
  UNIT_MILE,
]

export const EPSILON = 1e-6
export const PI = Math.PI
export const _2_PI = 2 * Math.PI
export const PI_2 = Math.PI / 2
export const _3_PI_2 = (3 * Math.PI) / 2
export const NORMALIZED_Y_AXIS = new Vector3(0, 1, 0)

export const KEYBOARD_BUTTON_CODE = {
  DELETE: 46,
  BACKSPACE: 8,
  ESC: 27,
  Z: 90,
  ALT: 18,
  C: 67,
  V: 86,
  CTRL: 17,
  ENTER: 13,
  TAB: 9,
  UP: 38,
  DOWN: 40,
  RIGHT: 39,
  LEFT: 37,
  ARROW_KEYS: [38, 40, 37, 39],
}

// Preferencias

export const GUIA2D = 'GUIA2D'
export const GUIA3D = 'GUIA3D'
export const UNIDADMEDIDA = 'UNIDADMEDIDA'
export const VERANGULOS = 'VERANGULOS'
export const C_LISOPARED2D = 'C/LISOPARED2D'
export const C_LISOPARED3D = 'C/LISOPARED3D'
export const C_LINEASCOTA = 'C/LINEASCOTA'
export const C_COTA = 'C/COTA'
export const ALTOPARED = 'ALTOPARED'
export const FONDOPARED = 'FONDOPARED'
export const T_REJILLA2D = 'T/REJILLA2D'
export const T_REJILLA3D = 'T/REJILLA3D'
export const ZOOM2D = 'ZOOM2D'
export const VER90 = 'VER90'
export const FONTS = 'FONTS'
export const T_REJILLATOTAL2D = 'T/REJILLATOTAL2D'
export const T_REJILLATOTAL3D = 'REJILLATOTAL3D'

// Valores 3D
export const ENV_MAP_INTESITY = 0.3
export const DARK_BLUE = '#3C476E'
export const GIZMO_Y_OFFSET = 8000
export const GIZMO_ROTATION = Math.PI / 2
export const ITEM_SCENE_SCALE = 1000
export const GIZMO_SCALE = 400
export const GIZMO_SCALE_3D = 600
export const GIZMO_LINE_WIDTH = 3

//Valores eventos
export const DOUBLE_CLICK_THRESHOLD = 500

// Valores luces
export const LIGHT_GIZMO_COLOR = ['#b7153d', '#b7153d', '#b7153d']
export const SHADOW_MAP_SIZE = [1024, 1024]
export const DISTANCE_FACTOR = 1000
export const LIGHT_MESH_HEIGHT_2D = 8000
export const LIGHT_MESH_SCALE = 5000
export const LIGHT_PIVOT_OFFSET = 50

//Spotlight 3d
export const SPOT_CAMERA_FAR = 10000
export const SPOT_CAMERA_NEAR = 0.1
export const SPOT_CAMERA_FOV = 90
export const SPOT_CAMERA_FOCUS = 1

//Pointlight 3d
export const POINT_CAMERA_NEAR = 0.1
export const POINT_CAMERA_FAR = 10000
export const POINT_SHADOW_BIAS = 0.000001

//Directional 3d
export const DIRECTIONAL_SHADOW_BIAS = -0.001
export const DIRECTIONAL_CAMERA_NEAR = 0.1
export const DIRECTIONAL_CAMERA_FAR = 10028
export const DIRECTIONAL_CAMERA_LEFT = -5028
export const DIRECTIONAL_CAMERA_RIGHT = 5028
export const DIRECTIONAL_CAMERA_BOTTOM = -5028
export const DIRECTIONAL_CAMERA_TOP = 5028

//Cubecamera
export const CUBE_CAMERA_RESOLUTION_2D = 16
export const CUBE_CAMERA_RESOLUTION_3D = 256
export const CUBE_CAMERA_POSITION = new Vector3(0, 0, 0)

// TODO @Vikms95 test if this is a reasonable threshold
export const CUBE_CAMERA_FAR_ITEM = 5000
export const CUBE_CAMERA_NEAR_ITEM = 0.1
export const CUBE_CAMERA_FRAMES = 1
export const CUBE_CAMERA_FRAMES_ITEM = 5
export const CUBE_CAMERA_FAR = 1
export const CUBE_CAMERA_FIXED_ROTATION = new Euler(0, Math.PI / 2, 0, 'XYZ')
export const ITEMS_REVERT_FIXED_ROTATION = new Euler(0, -Math.PI / 2, 0, 'XYZ')

//Area
export const AREA_DEFAULT_POSITION = new Vector3(0, 1, 0)
export const AREA_DEFAULT_ROTATION = new Euler(Math.PI / 2, 0, 0)

//3D
export const SELECTED_ITEM_COLOR = new Color('#99C3FB')

//Camera 3D
export const CAMERA_3D_NEAR = 2
export const CAMERA_3D_FAR = 50000
export const CAMERA_3D_FOV = 45
export const CAMERA_3D_ZOOM = 1
export const CONTROLS_3D_SMOOTH = 0.1
export const CONTROLS_3D_MIN_DISTANCE = 1000
// export const CONTROLS_3D_MAX_DISTANCE = 100000
export const CONTROLS_DOLLY_SPEED = 0.25

//Camera 3D
export const CAMERA_2D_NEAR = 0.1
export const CAMERA_2D_FAR = 10000
export const CAMERA_2D_SMOOTH = 10000
export const CAMERA_2D_MIN_POLAR = 0
export const CAMERA_2D_MAX_POLAR = 0
export const PAN_ACTION = 2

//Grid
export const GRID_FADE_DISTANCE = 100000
export const GRID_FADE_STRENGTH = 0
export const GRID_CELL_SIZE = 200
export const GRID_SECTION_SIZE = 1000
export const GRID_SECTION_COLOR = '#e0dede'
export const GRID_CELL_COLOR = '#f2f2f2'
export const GRID_CELL_THICKNESS = 1.25
export const GRID_SECTION_THICKNESS = 1
export const GRID_SCALE = 1
export const GRID_SIZE = 20000
export const GRID_DETAIL = 1
export const GRID_POSITION = new Vector3(0, 0, 0)
export const GRID_BACKGROUND_COLOR = new Color('white')
export const GRID_SIDE = BackSide

//Keycodes
export const ENTER_KEY = 'Enter'

//Path tracing
export const PATHTRACING_TILES = { x: 2, y: 2 }
export const PATHTRACING_BOUNCES = 4
export const PATHTRACING_SAMPLES = 2
export const PATHTRACING_RESOLUTION = 0.75
export const PATHTRACING_BACKGROUND_INTENSITY = 1
export const PATHTRACING_ALPHA = 0

// Drawing
export const SNAP_RANGE_DIRECTIONAL_KEY = 100
export const DEFAULT_SUGGESTED_ROTATION = Math.PI / 2

//Colisions
export const COLLISION_WALL_RANGE_THICKNESS = 750

//Base walls values
export const WALL1_VALUES = { id: 'pared1', x: 2075, z: 0 }
export const WALL2_VALUES = { id: 'pared2', x: 0, z: 2075 }
export const WALL3_VALUES = { id: 'pared3', x: -2075, z: 0 }
export const WALL4_VALUES = { id: 'pared4', x: 0, z: -2075 }
